services:
  api:
    build: .
    image: registry.cn-heyuan.aliyuncs.com/leo03w/maccy-server:v0.1.0
    environment:
      TZ: Asia/Shanghai
    command: ["-config", "/etc/maccy-server/config.yaml"]
    volumes:
      - "./config.yaml:/etc/maccy-server/config.yaml:ro"
      - "maccy-zvec-data:/opt/maccy-server/.zvec"
    ports:
      - "127.0.0.1:8080:8080"
    restart: always
    networks:
      - db_core

networks:
  db_core:
    external: true
    name: leo_db_core

volumes:
  maccy-zvec-data:
